### ISSUE TITLE
[ModalBody] ngClass will not work on Modal Body

### ISSUE THREAD

**Issue by mohammedzamakhan** [momentum-design/momentum-ui#105]
Hey there! Before you post an issue here, did you try reporting this to the "Collab UI Q&A" space in Webex Teams? Please ask about your issue there before creating a new GitHub issue.

**I'm submitting a ...**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/collab-ui/collab-ui-angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Component Affected**
Modal Body, Modal Header, Modal Footer, List, List Item

**Current behavior**
ngClass is not supported for the components mentioned above because of the way its accessing class as Input

Avoid 

```
@Input() class
```

**Expected/desired behavior**
ngClass should be supported.

**Reproduction of the problem**
Here is a sample reproduction: https://stackblitz.com/edit/angular-cmid9w?file=src%2Fapp%2Fapp.component.html (check HelloComponent)

Solution: https://github.com/collab-ui/collab-ui-angular/pull/16#discussion_r259599236

@ArthusLiang @pauljeter @elenagiere 
**Please tell us about your environment:**

* **Toolkit Version version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by ArthusLiang** [comment]
I tried to remove @Input() class, but I found the problem is caused by @HostBinding('class') i the sample. But I still can not fix it, just want to know if CDK overlay has some other side effects.
