### ISSUE TITLE
[Angular] Collab UI Components should be converted to Web Components

### ISSUE THREAD

**Issue by mohammedzamakhan** [momentum-design/momentum-ui#106]
Hey there! Before you post an issue here, did you try reporting this to the "Collab UI Q&A" space in Webex Teams? Please ask about your issue there before creating a new GitHub issue.

**I'm submitting a ...** (check one with "x")

```
- [ ] bug report
- [x] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/collab-ui/collab-ui-angular/blob/master/CONTRIBUTING.md#-got-a-question-or-problem
```

**Component Affected**
All

**Current behavior**
Web Components are not generated

**Expected/desired behavior**
Using Angular Elements, the components in Collab UI can be converted into Web Components, so that they can be used in any other application, even in Vanilla JS app or with any other framework https://custom-elements-everywhere.com/

**Comment by pauljeter** [comment]
We will look into implementing this in the future.
