### ISSUE TITLE
[Alert] Add timeouts to dismiss alerts

### ISSUE THREAD

**Issue by aimeex3** [momentum-design/momentum-ui#110]
Allow alerts to take in a timeout prop so it can be dismissed after a certain amount of time

## Issue Type
Feature Request

## Component or Pattern Affected
Alert/AlertContainer

## Steps to Reproduce (for bugs)
1. 

1. 

1. 

1. 

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by aimeex3** [comment]
@pauljeter, can we also allow `<AlertContainer>` to pass a list of `<Alert>` components instead of calling the `ref` of the AlertContainer to add items to the list? Should that be a separate ticket?

**Comment by bfbiggs** [comment]
Will expect app to handle timeouts, but will fix component architecture.
