### ISSUE TITLE
[Core] The help text under the radio button (and checkbox) issues

### ISSUE THREAD

**Issue by jepeng214** [momentum-design/momentum-ui#145]
On AngularJS, the help text under the radio button (and checkbox) has three problems:

1. The help text is not aligned with the radio label.
1. The help text does not have the same color as the label when it is disabled. See screenshot below.
1. The help text has the font size the same as the label. On UX mock-up, the help text font size should be smaller than the label.

## Issue Type
Bug Report

## Component or Pattern Affected

Radio button and Checkbox

## Expected Behavior

![image](https://user-images.githubusercontent.com/5296518/54954192-12849900-4f18-11e9-959c-371afae57f18.png)

## Steps to Reproduce (for bugs)

1. https://admin.webex.com
1. 
1. 
1. 

## Your Environment

* Library: AngularJS
* Version used: 10.0.0
* Browser Name and version: Chrome 72
* Operating System and version: macOS 10.14.3
* Link to your project: https://admin.webex.com

**Comment by pauljeter** [comment]
Fixed by #375
