### ISSUE TITLE
Support routerLinkActive

### ISSUE THREAD

**Issue by mohammedzamakhan** [momentum-design/momentum-ui#180]
## Issue Type

Support Request

## Component or Pattern Affected

ListItemComponent
Router Link Active takes care of check if if the route is active, and then adds the respective class

```
<a cui-list-item routerLink="/home" routerLinkActive="active"  [active]="true" label="Home"></a>
```

but if we pass active manually, we will have to logic to check if the route is active or not, and pass the state of activeness

```
<a cui-list-item routerLink="/home"  [active]="true" label="Home"></a>
```

## Expected Behavior

We should be able to use routerLinkActive to be used along with routerLink without any issues

## Current Behavior

I have to click on the list item twice to apply the routerLinkActive class to the element

## Possible Solution

Remove the active input probably from the component

## Steps to Reproduce (for bugs)

1.  <a cui-list-item routerLink="/home" routerLinkActive="active" label="Home"></a>
1. Be on a different route
1. Click on home, you will see that the link does not have the class active
1. Click it again, it will have the class active

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by bfbiggs** [comment]
Closing as angular library has been forked and removed.
