### ISSUE TITLE
Add responsive display classes

### ISSUE THREAD

**Issue by mcanfield** [momentum-design/momentum-ui#196]
## Issue Type
Feature Request

## Component or Pattern Affected
core css

## Expected Behavior
Responsive classes that hide/show elements based on momentum-ui breakpoints.

## Current Behavior
Currently elements can only be resized or realigned based on standard column breakpoint sizes. They cannot be omitted without custom css being written.

## Possible Solution
Bootstrap has display utilities that do this and more: https://getbootstrap.com/docs/4.1/utilities/display/

## Steps to Reproduce (for bugs)
N/A

## Context
The ability to hide/show elements like labels next to icons or illustrations as screen sizes change. I rather not depend on SASS in my project, but would need to in order to keep my custom responsive display breakpoints in sync with momentum-ui SASS variables.

## Your Environment
* Library: Core, Angular
* Version used: 14.0.0
* Browser Name and version: Chrome 73
* Operating System and version: macOS 10.14.3
* Link to your project:

**Comment by mcanfield** [comment]
Looks like I missed this one in the source code: https://github.com/momentum-design/momentum-ui/blob/master/core/scss/utilities/responsive.scss

Since this looks to be based off of bootstrap, please review adopting latest 4.1 spec, or just close this issue. Thanks!

**Comment by pauljeter** [comment]
We currently have responsive classes based on Bootstrap 3's classes. We will park this to look into updating them in the future.
