### ISSUE TITLE
[ComboBox] add 'ariaLabel' and 'ariaDescribedBy' props for accessibility

### ISSUE THREAD

**Issue by AMANDUA** [momentum-design/momentum-ui#198]
add 'ariaLabel' and 'ariaDescribedBy' props to ComboBox for accessibility

## Issue Type

Feature
## Component or Pattern Affected

ComboBox
## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Library: React
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by pauljeter** [comment]
Fixed in #199
