### ISSUE TITLE
[Popover] Handle isDynamic and isContained (including custom padding prop)

### ISSUE THREAD

**Issue by aimeex3** [momentum-design/momentum-ui#204]
When adding isContained, depending on the position of the avatar, the popover stretches. I tried using isDyanmic too and that didn't work. We want the popover to show within the browser window so if it's near the top or near the bottom, you can still see the popover contents. It doesn't need to be contained within the space list (which is what isContained would do I believe) I think isDynamic might be the correct prop to use, but doesn't look like it works correctly either

For the dynamic popover, is it possible to add a custom margin like 12px margin from the edge so that it doesn't go to the edge of the screen?

## Issue Type
Bug Report

## Component or Pattern Affected
Popover

## Expected Behavior
If popover is triggered near the button of the screen and isDynamic is set to true, it should dynamically open upwards and show the full contents of the popover. Same logic applies if it's near the top of the app.

## Current Behavior
![](https://user-images.githubusercontent.com/819823/57035142-29e52f00-6c06-11e9-9410-dccac939e904.png)
if using isContained

## Steps to Reproduce (for bugs)

1. 
1. 
1. 
1. 

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by bfbiggs** [comment]
Consider adding prop called isArrowDynamic which doesn't resize the original container but allows arrow to move along the side of the container.
