### ISSUE TITLE
Momentum UI does not load in IE11

### ISSUE THREAD

**Issue by aimeex3** [momentum-design/momentum-ui#205]
With the latest updates, momentum ui does not load in IE 11. I get a blank screen on the momentum design website as well as the web client

## Issue Type
Bug Report

## Component or Pattern Affected
App will not load

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by adamweeks** [comment]
It appears the files in `@momentum-ui/utils/lib/` aren't transpiling to ES5 properly and still have `const` keywords in them.

We've got it working with a workaround by specifying that folder to be processed by babel/webpack.
