### ISSUE TITLE
momentum-ui affecting the timepicker dropdown menu by partial cut off during dropdowns

### ISSUE THREAD

**Issue by nitinsi27** [momentum-design/momentum-ui#221]
## Component or Pattern Affected
Timepicker Dropdown

## Expected Behavior

DropDown for Timepicker should be popped up above the Time pane if there is no space left below in the form. 

## Current Behavior
Unable to modify Holiday Start and End Time since the control to increase/decrease the time is not visible with after higher number of holidays are added, ~20.
This looks to be an issue in the Time Picker and possibly the fixed location of the Time picker and drop-down always opening up below inside a large modal is playing a role here. Maybe the dropdown should offset the limited space left and pop up above the Time panel.

## Possible Solution
Make it responsive.

## Steps to Reproduce (for bugs)
1. Add 20 Holidays in the AutoAttendant builder.
2. Try updating the Holiday start and end time. 
3. Since the complete form will be filled up, need to reduce the browser zoom to view the timepicker. For 20+ holidays need to reduce to 25% where it becomes hard to view and update.

## Context
Customer's AA update impacted as they have higher number of Holidays in the calendar.

## Your Environment
CES - AA Builder. Leverages UI-Toolkit.
<img width="354" alt="Adding holiday (zoom 50%) (2)" src="https://user-images.githubusercontent.com/20330067/57687777-eb317a80-75f0-11e9-9bb7-49cfe4b4cf7c.PNG">
<img width="479" alt="Adding holiday (Zoom 67%) (2)" src="https://user-images.githubusercontent.com/20330067/57687778-eb317a80-75f0-11e9-9bea-8b6bbd47bc33.png">

**Comment by pauljeter** [comment]
Fixed by #219

**Comment by nitinsi27** [comment]
Posting here as well.

Hi Peter,
I am assuming the changes will fix the TimePicker issue for the Open Hours Schedule along with the Holiday Schedule. Though the behavior and misalignment are similar, so wanted to confirm if it fixes both the schedules. Attaching some snippets from Open Hours.

Thanks
Nitin

<img width="867" alt="OPEN_HOURS_working_no_zoom" src="https://user-images.githubusercontent.com/20330067/58355027-fa51cd00-7e27-11e9-8891-b582e44d0903.png">
<img width="867" alt="OPEN_HOURS_non_working_no_zoom" src="https://user-images.githubusercontent.com/20330067/58355028-fa51cd00-7e27-11e9-86c5-46df18b3e6ef.png">
<img width="867" alt="OPEN_HOURS_working_after_zoomout" src="https://user-images.githubusercontent.com/20330067/58355029-fa51cd00-7e27-11e9-9a59-79aa41373de8.png">

**Comment by nitinsi27** [comment]
![timepicker_dropdown_invisible_67pcnt_zoom](https://user-images.githubusercontent.com/20330067/59334002-66e51c80-8cae-11e9-8cd8-2b4b4215a2e8.JPG)
![timepicker_dropdown_visible_50pcnt_zoom](https://user-images.githubusercontent.com/20330067/59334010-6ba9d080-8cae-11e9-932d-0d31a3a1f5c0.JPG)
