### ISSUE TITLE
Woff font files are corrupt for IE11

### ISSUE THREAD

**Issue by adamweeks** [momentum-design/momentum-ui#222]
`woff` font files from core and icons are throwing the following error when loading on IE11:

```
@font-face failed WOFF integrity check
```

Manually processing the ttf files from the node modules and converting them into woff files resolves the issue, so there must be some issue with the generator.

**Comment by tbassetto** [comment]
> Manually processing the ttf files from the node modules and converting them into woff

With which tool are you doing this conversion?

The font generator package we are using is just a thin wrapper on top of actual font conversion tools. 

Ideally the generated WOFF file should work in IE 11, but in the meantime a quick "fix" is to serve the current TTF file to IE 11. I have a PR ready.

**Comment by adamweeks** [comment]
@tbassetto I loaded the ttf version into https://transfonter.org/ and then verified the woff file generated on http://validator.fontbureau.com/

The current woff version fails validation.
