### ISSUE TITLE
Minor Styling bug (TopBar): Cisco logo is not being pushed to the right 

### ISSUE THREAD

**Issue by akoushke** [momentum-design/momentum-ui#239]
![Screen Shot 2019-05-13 at 9 45 20 AM](https://user-images.githubusercontent.com/14226615/58039507-d6b91a80-7ae7-11e9-92a8-de97dc058a8d.png)

Just a bit of left margin on the logo should fix this issue.

**Comment by tbassetto** [comment]
It's not just about adding margins.

If we look at the difference between the [pure HTML/CSS TopBar example from the documentation](https://momentum.design/components/top-bar/code), and the code generated by the React component, we can see that the class `row` is missing from `<div class="md-top-bar__container">`. By just adding this class, the default template in the react starter kit would look correct:
![Screenshot_2019-06-07 Momentum UI React Starter(1)](https://user-images.githubusercontent.com/211630/59086968-ace35e80-8903-11e9-8907-8adf7449d753.png)

I think that the Angular components have the same issue.

**Comment by akoushke** [comment]
@bfbiggs  duplicate?

**Comment by tbassetto** [comment]
PR #261 actually didn't close it, is it possible to reopen this issue? :)
