### ISSUE TITLE
[Select] choices aren't totally highlighted

### ISSUE THREAD

**Issue by mathsusan** [momentum-design/momentum-ui#272]
## Component or Pattern Affected

Select
## Expected Behavior

when I hover over the items in the select the whole line should highlight

## Current Behavior

only about 60% of the line highlights
<img width="281" alt="Screenshot 2019-06-20 at 9 33 59 PM" src="https://user-images.githubusercontent.com/8696929/59865265-3ce6c680-934e-11e9-9cda-51997fb17c6b.png">

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Context

overrode the css to correct

## Your Environment

* Library: 
Angular
* Version used: 
latest
* Browser Name and version: 
chrome
* Operating System and version: 
Mac 
* Link to your project:

**Comment by karsumit94** [comment]
Added this snippet for a temporary workaround 
`.md-list {
  width: 100%;
}`

**Comment by daanishnasir** [comment]
Closing as fixed.
