### ISSUE TITLE
Overlay z-index affecting select options on sidepanel

### ISSUE THREAD

**Issue by sani12** [momentum-design/momentum-ui#310]
## Issue Type 
Bug

## Component or Pattern Affected

md-select -- Select options getting hidden by the cdk-overlay component z-index being lower than the side-panel.
core/scss/components/overlay/event-overlay.scss
/Users/sani/atlas/momentum-ui/core/scss/ng/settings/settings.scss
$zindex-top-bar-fixed:        1030;

## Current Behavior
Options are listed, but hidden.
<img width="821" alt="Screen Shot 2019-08-06 at 3 05 59 PM" src="https://user-images.githubusercontent.com/25227559/62573484-c3eaf200-b85b-11e9-8930-c07eed55328e.png">

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by daanishnasir** [comment]
Reworking Select keeping this issue in mind.

**Comment by mathsusan** [comment]
solved by this PR https://github.com/momentum-design/momentum-ui/pull/343
