### ISSUE TITLE
[ButtonGroup] Pill Styles

### ISSUE THREAD

**Issue by bfbiggs** [momentum-design/momentum-ui#32]
Hey there! Before you post an issue here, did you try reporting this to the "Collab UI Q&A" space in Webex Teams? Please ask about your issue there before creating a new GitHub issue.

**I'm submitting a ...**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/collab-ui/collab-ui-core/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Component Affected**
ButtonGroup

**Current behavior**
Active style can't be modified because it's being programatically removed in the ButtonGroup component.

**Expected/desired behavior**
If the default active style should be trasparent, than that style could be applied in the css so that it can be overwritten.

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via images or video.

**Please tell us about your environment:**

* **Toolkit Version version:**

* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

**Comment by pauljeter** [comment]
Ben Biggs ( https://app.asana.com/0/436081154253395/list ), follow up with the Web Client team for more clarification on this issue.
