### ISSUE TITLE
[Sidepanel] Links are wonky

### ISSUE THREAD

**Issue by mathsusan** [momentum-design/momentum-ui#33]
**I'm submitting a ...**  (check one with "x")

- [x] bug report
- [ ] feature request
- [ ] support request => Please do not submit support request here, instead see https://github.com/collab-ui/collab-ui-core/blob/master/CONTRIBUTING.md#-got-a-question-or-problem

**Component Affected**

sidepanel
**Current behavior**

text in sidepanel problems, things that are not links highlight blue when I hover and things that are only part of them highlight in some cases
**Expected/desired behavior**
things that are not links should not highlight and things that are links should

**Reproduction of the problem**
If the current behavior is a bug or you can illustrate your feature request better with an example, please provide the steps to reproduce and if possible a minimal demo of the problem via images or video.

[sidepanel.zip](https://github.com/collab-ui/collab-ui-core/files/2548950/sidepanel.zip)

**Please tell us about your environment:**
MAC OS
* **Toolkit Version version:**
10.33.2
* **Browser:** [all | Chrome XX | Firefox XX | IE XX | Safari XX | Mobile Chrome XX | Android X.X Web Browser | iOS XX Safari | iOS XX UIWebView | iOS XX WKWebView ]

Chrome

**Comment by pauljeter** [comment]
@kbsmth, need to get design update

**Comment by pauljeter** [comment]
This will be solved with the new list item styles.
