### ISSUE TITLE
Unable to import scss in global scope

### ISSUE THREAD

**Issue by silviujingoi** [momentum-design/momentum-ui#363]
I'm trying to import the scss module globally

```
:global {
  @import '~@momentum-ui/core/scss/momentum-ui';
}
```

But I'm getting the following error:

> Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleBuildError: Module build failed (from ./node_modules/css-loader/dist/cjs.js):
Error: Missing whitespace before :global

**Comment by pauljeter** [comment]
I believe this is a sass loader [issue](https://github.com/webpack-contrib/sass-loader/issues/448#issuecomment-299731035). Try escaping using `\:global` syntax.
