### ISSUE TITLE
[Topbar] Blocks Space and Enter key press events on the whole document

### ISSUE THREAD

**Issue by d-silvas** [momentum-design/momentum-ui#410]
The TopbarMobileComponent blocks Space and Enter key press events on the whole document.

## Issue Type
Bug Report

## Component or Pattern Affected

TopbarMobileComponent

## Expected Behavior

Space and Enter key presses should be recognized in other parts of the application.

## Current Behavior

An example: spaces can't be introduced in any text input element.

## Possible Solution

The HostListener `handleKeydown` is listening for keydown events on the whole document. I think the `e.preventDefault()` call is what is causing the issue.

## Steps to Reproduce (for bugs)

1. Create a component with template as follows:
```
<md-top-bar-mobile></md-top-bar-mobile>
<input type="text">
```
2. Type some characters including spaces in the input box.

## Context

Trying to include a responsive top bar in an application that contains forms.

## Your Environment

* Library: Angular
* Version used: 9.2.8
* Browser Name and version: Chrome 77, Firefox 69
* Operating System and version: Windows 10, Ubuntu 19

**Comment by pauljeter** [comment]
Fixed by #414
