### ISSUE TITLE
[Popover] Ability to set a max-width for the pop-over

### ISSUE THREAD

**Issue by karsumit94** [momentum-design/momentum-ui#427]
## Issue Type 
Feature Request

## Component or Pattern Affected 
Popover

## Expected Behavior
Ability to set a max-width for the badge pop-over for mdPopover attribute.

## Current Behavior
It takes the entire width of the content in the pop-over. While using template it doesn't show any content.

## Your Environment
* Library: Angular 
* Version used: 7.3.0
* Browser Name and version: Chrome 77.0.3865 
* Operating System and version: Mac OS X 10.14

**Comment by bfbiggs** [comment]
Closing as angular library has been forked and removed.
