### ISSUE TITLE
[angularJS] Warning/Error messages generated for md-select are not showing proper icon

### ISSUE THREAD

**Issue by rovshenn** [momentum-design/momentum-ui#429]
Warning/Error messages generated for md-select are not showing proper icon and the message and icon (a Chinese character) are misaligned.

## Issue Type
Bug Report

## Component or Pattern Affected

md-select

## Expected Behavior

a warning/error icon should show and the message should show next to it

## Current Behavior

At the moment the icon is showing a different character instead of showing a warning/error icon.

![Screen Shot 2019-10-16 at 12 51 11 PM](https://user-images.githubusercontent.com/1402925/66944893-b009fc00-f013-11e9-8f53-d93a12b09641.jpg)
![Screen Shot 2019-09-26 at 12 30 33 PM](https://user-images.githubusercontent.com/1402925/66944939-c912ad00-f013-11e9-95d9-8b5200f33ce4.jpg)

## Possible Solution

When building the error messages for md-select a proper css needs to be used to render a warning/error icon correctly.

## Steps to Reproduce (for bugs)

1. 
2.
3.
4.

## Your Environment

* Library: 
AngularJS
* Version used: 
13.0.11
* Browser Name and version: 
Chrome 77
* Operating System and version: 
macOS
* Link to your project:

**Comment by pauljeter** [comment]
Fixed in #463
