### ISSUE TITLE
Updated aria-label for mute icon/button in example

### ISSUE THREAD

**Issue by sammythesm** [momentum-design/momentum-ui#443]
![09_39_34](https://user-images.githubusercontent.com/4318804/67536195-ee528b80-f6a3-11e9-9f35-e6ad7793e116.jpg)

## Issue Type
Bug Report

## Component or Pattern Affected
Icon

## Expected Behavior
"Mute" as the example aria tag

## Current Behavior
"For the win" is the aria tag in the example

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by pauljeter** [comment]
Fixed by #453
