### ISSUE TITLE
Getting this error Cannot find module '@angular/platform-browser/src/security/dom_sanitization_service' with Angular 8.

### ISSUE THREAD

**Issue by eswoohy** [momentum-design/momentum-ui#444]
Getting the below error when I import the SidebarNavItemComponent in my Angular 8 test sample project.

ERROR in node_modules/@momentum-ui/angular/pagination/pagination.service.d.ts(26,37): error TS2307: Cannot find module '@angular/platform-browser/src/security/dom_sanitization_service'

**Comment by Adrian1907** [comment]
https://github.com/scaleflex/ng-cloudimage-responsive/issues/6 is about the same and is closed, but it is not clear what to do to resolve the error

**Comment by bfbiggs** [comment]
Closing as angular library has been forked and removed.

**Comment by Amir425** [comment]
😍😍yes I have a solution, just follow the error path

ERROR in node_modules/angular-calendar-year-view/lib/angular-calendar-year-view.component.d.ts(5,28): error TS2307: Cannot find module '@angular/platform-browser/src/security/dom_sanitization_service'.

in your code editor, You will find this line showing error

"readonly style: import("@angular/platform-browser/src/security/dom_sanitization_service").SafeStyle;"

comment this whole line and paste under this commented line

readonly style: SafeStyle;
✔✔✔✔
