### ISSUE TITLE
Angular: md-tooltip does not follow specifications

### ISSUE THREAD

**Issue by kjeree** [momentum-design/momentum-ui#494]
## Issue Type
Bug report
## Component or Pattern Affected
Angular's `md-tooltip`

## Expected Behavior
The tooltip text should be centered, according to examples at https://momentum.design/components/tooltip/usage

## Current Behavior
The tooltip text is left-aligned.

## Possible Solution
Will create a PR.

## Context
Code does not seem to follow specifications.

## Your Environment

* Library: Angular
* Version used: Latest master
* Browser Name and version: All browsers
* Operating System and version: All operating systems
* Link to your project: N/A

**Comment by bfbiggs** [comment]
Closing as angular library has been forked and removed.
