### ISSUE TITLE
Tabs component fails to properly utilize [focus] property when using ngFor

### ISSUE THREAD

**Issue by Heebs13** [momentum-design/momentum-ui#547]
Momentum UI tabs component documented here:

https://momentum.design/components/tabs/code

In Angular, property [focus] is meant to allow a tab to be selected by default when a user arrives at the component. However, this will only work if each tab is built separately and cannot be used in conjunction with ngFor.

## Issue Type
Bug Report

## Component or Pattern Affected
MD Tabs

## Expected Behavior
When using momentum design tabs component, we should be able to use ngFor and still get the default selection behavior.

## Current Behavior
When using ngFor in conjunction with momentum tabs, default selection fails.

## Steps to Reproduce (for bugs)
1. Create a component using md-tabs
2. Have the md-tab elements created by an ngFor loop
3. Observe that no tab is selected by default.

## Your Environment
* Library: Angular
* Version used: Momentum 4.0.0
* Browser Name and version: Google Chrome
* Operating System and version: Mac OS

**Comment by bfbiggs** [comment]
Closing as angular library has been forked and removed.
