### ISSUE TITLE
[Menu] Menu item disabled state

### ISSUE THREAD

**Issue by mafrobert** [momentum-design/momentum-ui#583]
## Issue Type
Feature Request

## Component or Pattern Affected

Menu item

## Expected Behavior

Since menu-item is actually the list-item, it should have support for disabled state, an input that's attached to the list-item and provide according style.
<img width="134" alt="Screen Shot 2020-04-03 at 7 26 57 PM" src="https://user-images.githubusercontent.com/22702708/78390471-501d0700-75ed-11ea-83a9-d2b424d709e9.png">

## Current Behavior

Menu item does not support a disabled input.
<img width="134" alt="Screen Shot 2020-04-03 at 7 27 47 PM" src="https://user-images.githubusercontent.com/22702708/78390671-9c684700-75ed-11ea-8727-cbb0558748ba.png">

## Possible Solution

`disabled` property should be added as input to `MenuItemComponent` and set to false by default.

## Steps to Reproduce (for bugs)

1. Create a `md-menu`.
2. Add menu items.
3. Try to disable any of the menu items.

## Context

Trying to dynamically disable the menu's items was not possible without adding local changes.

## Your Environment

* Library: Angular
* Version used: 19.4.5
* Browser Name and version: Chrome Version 80.0.3987.149 (Official Build) (64-bit)
* Operating System and version: macOS 10.15.4

**Comment by bfbiggs** [comment]
Closing as angular library has been forked and removed.
