### ISSUE TITLE
Angular 9 failed to compile

### ISSUE THREAD

**Issue by philjones88** [momentum-design/momentum-ui#597]
## Issue Type
Bug Report

## Component or Pattern Affected
Angular

## Expected Behavior
To build

## Current Behavior
```
Failed to compile.

The target entry-point "@momentum-ui/angular" has missing dependencies:
 - lodash-es/reject
 - @angular/cdk/text-field
 - @angular/cdk/coercion
 - @angular/cdk/platform
 - lodash-es/find
 - lodash-es/isObject
 - @angular/cdk/a11y
 - lodash-es/isEqual
 - @angular/cdk/overlay
 - @angular/cdk/portal
 - @angular/cdk/keycodes
 - lodash-es/findIndex
 - lodash-es/uniqueId
```

## Steps to Reproduce (for bugs)
Try and follow the README.

Added it with yarn.

Added it to AppModule.

Instructions are unclear also. You suggest "Then import the components into the components where you will use them." but Angular doesn't allow you to do that anymore. It's all NgModule based.

Do you not have a full example Angular app?

The documentation is very lacking.

## Your Environment
Angular 9 with Ivy
MacOS
Node LTS v12

* Link to your project:

**Comment by philjones88** [comment]
Is the documentation missing references to the required peer dependencies?

https://github.com/momentum-design/momentum-ui/blob/master/angular/src/lib/package.json#L33

**Comment by bfbiggs** [comment]
Will not fix - since Angular project has been forked.
