### ISSUE TITLE
Use className or clsx package for adding multiple classes

### ISSUE THREAD

**Issue by mohammedzamakhan** [momentum-design/momentum-ui#62]
Currently, I see that multiple class names are added using javascript strings, it would be better if we use clsx package which is 1.2Kb only for managing it.

## Issue Type

Feature Request

## Component or Pattern Affected
Most of them

## Current Behavior

```jsx
<div
        className={
          'cui-button-group' +
          `${(theme && ` cui-button-group--${theme}`) || ''}` +
          `${(justified && ` cui-button-group--justified`) || ''}` +
          `${(type && ` cui-button-group--${type}` || '')}` +
          `${(className && ` ${className}`) || ''}`
        }
>
</div>
```

## Possible Solution

Using clsx

```jsx
<div
        className={
          clsx('cui-button-group', {
            'cui-button-group--justified': justified,
            [`cui-button-group--${theme}`]: theme,
            [`cui-button-group--${type}`]: type
          }, className)
        }
>
</div>
```

This is much cleaner, as you do not have to deal with spaces in the class names and also empty string if the condition is undefined.

## Steps to Reproduce (for bugs)

1. 
1. 
1. 
1. 

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by pauljeter** [comment]
We will look at implementing this in the future
