### ISSUE TITLE
Country Code Values Do Not Fit Within Combobox At Certain Screen Widths

### ISSUE THREAD

**Issue by jameswhitely** [momentum-design/momentum-ui#816]
## Issue Type
Bug report

## Component or Pattern Affected
md-combobox
md-input

## Expected Behavior
The country code values fit within the combobox and encompassed input within all supported screen widths.

## Current Behavior
Country code values are not fully displaying within the combobox and encompassed input at certain supported screen widths.

![Screen Shot 2021-03-04 at 11 37 08 AM](https://user-images.githubusercontent.com/80547213/111009610-1a86af00-8362-11eb-965c-09e968b0bd57.png)

## Steps to Reproduce (for bugs)

1. Login into the app as a doctor on a small device that has a screen width of minimum of 320px (Ex: iPhone SE/5) using portrait mode
2. Click Make a Phone call
3. Select the country code dropdown list

## Context
The md-combobox component is being used within the Instant Webex project as part of a feature allowing dial-out to meeting participants. We are leveraging Momentum's country code library in service of this as well.

Accepted screen widths for the Instant Webex project are not uniformly defined but in general seem have a floor of 320px width, with 550px width being the breakpoint for portrait mode display.

## Your Environment
Local dev using the PROD Webex services as a backend.

**Comment by futurethang** [comment]
@jameswhitely Have you tried setting a style override for that breakpoint by using the part selector we recently added? something kinda like 
```css
md-phone-input::part(combobox) {
  font-size: .5rem;
}
```
