### ISSUE TITLE
Add US flag to phone input country code dropdown box

### ISSUE THREAD

**Issue by ccorCis** [momentum-design/momentum-ui#827]
In the PhoneInput web component, the US flag picture was added to the country code dropdown box.

## Issue Type
Feature Request

## Component or Pattern Affected

<PhoneInput />

## Expected Behavior

Desired Outcome in image below:
<img width="359" alt="countryFlag" src="https://user-images.githubusercontent.com/79867310/111530037-d6fcbe00-8730-11eb-8334-b0aad64dadfb.png">

## Current Behavior

<img width="385" alt="noFlag" src="https://user-images.githubusercontent.com/79867310/111530735-a8cbae00-8731-11eb-885e-37576086df77.png">

**Comment by futurethang** [comment]
Closed with #855
