### ISSUE TITLE
part selector is missing on dropdown header label 

### ISSUE THREAD

**Issue by merajcal** [momentum-design/momentum-ui#860]
To customise the dropdown  label (e.g. pill shaped dropdown), there is no part selector available on the dropdown label element.pt

## Issue Type
 Bug Report 

## Component or Pattern Affected
Dropdown

## Expected Behavior
after allowing part on label element , dropdown can be displayed in pill shape

## Current Behavior
Not able to make dropdown as pill shaped

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Library: 
* Version used: 
* Browser Name and version: 
* Operating System and version: 
* Link to your project:

**Comment by futurethang** [comment]
Closed by #861
